### ISSUE TITLE
Bash Injection

### ISSUE THREAD

**Issue by pro-coder69** [GDGVIT/groff-editor-backend#21]
## Fill in the blanks

```
MONGO_URL=mongodb+srv://groff:groff___@cluster0-jtj9m.mongodb.net/_______?retryWrites=true&w=majority
MONGO_PASS=groff___
YOUR_CLIENT_SECRET=DPnUJnSAQm__-caUy_Kk_tUz
CLIENT_SECRET=jeLeMtdWs____T7dE__CEz_Yd
```

No point trying to fix it I'll get it again :1st_place_medal:

**Comment by L04DB4L4NC3R** [comment]
Fixed in a recent commit. Haha you are welcome to try. We will be happy to maKe our project more secure using the inputs we get from your attacks :)

**Comment by L04DB4L4NC3R** [comment]
We will add the link in the repo once we have this project in production

**Comment by pro-coder69** [comment]
Is it fixed? @L04DB4L4NC3R

**Comment by pro-coder69** [comment]
```
CLIENT_ID=1077010214943-1pdf3q1jcf0r89pt1hqfkec1i93uatnf.apps.googleusercontent.com
CLIENT_SECRET=jeLeMtdWsainT7dE55CEz6Yd
BACKEND_PORT=3000
MONGO_PASS=groff123
MONGO_URL=mon-godb+srv://groff:groff123@cluster0-jtj9m.mongodb.net/pragati?retryWrites=true&w=majority
JWT_KEY=secret
YOUR_CLIENT_ID=406278326181-82dqap6rfv8lmdi6bmo7j18jrfj2k45c.apps.googleusercontent.com
YOUR_CLIENT_SECRET=DPnUJnSAQm13-caUy0Kk1tUz
YOUR_REDIRECT_URL=https://local-host:3000/auth/google
NUM_HASH=11
HASH_TYPE=B4c0/
```
Nice try but there's still issues. No censorship this time. :parachute:

**Comment by L04DB4L4NC3R** [comment]
The latest changes are not in prod right now. Will open this if this is still an issue after they are deployed

**Comment by pro-coder69** [comment]
> The latest changes are not in prod right now. Will open this if this is still an issue after they are deployed

But the changes were deployed, it's still broken.

**Comment by hash-king** [comment]
**LMAO** @pro-coder69  @L04DB4L4NC3R I

**Comment by hash-king** [comment]
Tic Toc Tic Toc groff.******.*** editor.******.***

**Comment by 1UC1F3R616** [comment]
@hash-king editor.dscvit.com, groff.dscvit.com We all know how to use amass, Sublist3r, waybackurls. For you, I advise to use Tier-S tools, hope u get what I mean. Also, for ur next recon try this `assetfinder -subs-only dscvit.com -silent | httpx -timeout 3 -threads 300 --follow-redirects -silent | rush 'hakrawler -plain -linkfinder -depth 5 -url {}' | grep "dscvit`
Do post ur next findings.

**Comment by 1UC1F3R616** [comment]
@pro-coder69 thanks for the help again, I have started counting you as an inner-core member now. You could have done whatever harm you want once getting into the server but instead of that you helped and waited for a fix, people really don't understand the impact unless not shown.

**Comment by 1UC1F3R616** [comment]
@pro-coder69  thanks for the help again, I have started counting you as a valuable person now. You could have done whatever harm you want once getting into the server but instead of that you helped and waited for a fix, people really don't understand the impact unless not shown.

**Comment by raysandeep** [comment]
@pro-coder69 Thanks for your help! 
Feel free to join our Discord Server: https://discord.com/invite/cWyEXgV
Our Discord server helps external contributors reach out to us and help us improve our projects and take them to the next level by providing their own contributions.

**Comment by 1UC1F3R616** [comment]
@pro-coder69 We have fixed all the identified bugs and it's in production mode now. We welcome you to pentest the web app.
But you must be following code-of-conduct added to repository, do read it before.

Url: editor.dscvit.com
Backend: groff.dscvit.com

Peace ✌🏻 be 1337 🥇

**Comment by pro-coder69** [comment]
Sorry, I was busy with newer, interesting projects by other people. By the way, nice COC.

```
MONGO_PASS=6jnUWHDb68PQe4yx
JWT_KEY=bxJ6KZ4yEX9yjzUk
REDIRECT_URI=https://editor.dscvit.com/home
NUM_HASH=10CLIENT_ID=1077010214943-1pdf3q1jcf0r89pt1hqfkec1i93uatnf.apps.googleusercontent.com
CLIENT_SECRET=jeLeMtdWsainT7dE55CEz6Yd
PORT=3000
MONGO_URL=mongodb+srv://groff:6jnUWHDb68PQe4yx@cluster0.lcstw.mongodb.net/groff?retryWrites=true&w=majority
HASH_TYPE=B4c0/
```
@L04DB4L4NC3R @1UC1F3R616 @hash-king @raysandeep

I am fresher please take me in DSC bhaiya!

**Comment by mdhishaamakhtar** [comment]
@L04DB4L4NC3R re open this issue

**Comment by raysandeep** [comment]
Hey @pro-coder69,

We appreciate your interest in our project. Our team of developers have identified the underlying issue. We had not considered the ```.so``` Groff command which let others output the .env file onto their pdf. We would have never been able to do it without your help and we really appreciate your contribution to our project. 

We would like to welcome you to our discord server and our telegram outer circle channel. Regarding recruitments, follow our Instagram page and other social media channels to get updated regarding recruitments. Please feel free to contact us if you find anything else!  🥂
